services:
  app:
    container_name: attendance-app
    build: .
    env_file:
      - .env
    expose:
      - '8001'
    command: sh -c "node src/index.js"   # match however main project starts
    networks:
      - shared-nginx-net
    restart: unless-stopped

networks:
  shared-nginx-net:
    external: true
    name: amp_portal_backend_app-network