services:
  app:
    container_name: attendance-app
    build: .
    env_file:
      - .env
    networks:
      - shared-nginx-net

networks:
  shared-nginx-net:
    external: true
    name: amp_portal_backend_app-network
